<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="Client3 Sanity"
           tests="1"
           failures="1"
           errors="0"
           skipped="0"
           time="127.095">
  <properties />
            <testcase name="EP_SignUpAndCBReservationTest1" time="127.095" classname="com.bhs.scripts.employeeportal.EP_CBAndInHomeReservations_Tests">
                <failure type="java.lang.AssertionError"
                  message="null"
              >
<![CDATA[java.lang.AssertionError: null
  org.testng.Assert.fail(Assert.java:94)
  org.testng.Assert.fail(Assert.java:101)
  com.bhs.util.REPORTER.LogEvent(REPORTER.java:722)
  com.bhs.util.REPORTER.catchException(REPORTER.java:1041)
  com.bhs.util.COMMON_METHODS.editAField(COMMON_METHODS.java:341)
  com.bhs.BusinessComponents.EP_BusinessComponents.EP_SignUpUser1(EP_BusinessComponents.java:2461)
  com.bhs.scripts.employeeportal.EP_CBAndInHomeReservations_Tests.EP_SignUpAndCBReservationTest1(EP_CBAndInHomeReservations_Tests.java:896)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
  org.testng.TestRunner.privateRun(TestRunner.java:767)
  org.testng.TestRunner.run(TestRunner.java:617)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
  org.testng.SuiteRunner.run(SuiteRunner.java:240)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
  org.testng.TestNG.run(TestNG.java:1031)
  org.testng.TestNG.privateMain(TestNG.java:1338)
  org.testng.TestNG.main(TestNG.java:1307)
]]>
      </failure>

          </testcase>
  
  
  
</testsuite>
