<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="CSCUSLNAH014094" name="com.bhs.scripts.employeeportal.EP_Home_Tests" tests="10" failures="0" timestamp="13 Mar 2014 19:31:01 GMT" time="582.873" errors="2">
  <testcase name="EP_MyAccount" time="63.417" classname="com.bhs.scripts.employeeportal.EP_Home_Tests">
    <error type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.fail(Assert.java:101)
	at com.bhs.util.REPORTER.LogEvent(REPORTER.java:722)
	at com.bhs.util.REPORTER.catchException(REPORTER.java:1041)
	at com.bhs.util.COMMON_METHODS.editAField(COMMON_METHODS.java:306)
	at com.bhs.BusinessComponents.EP_BusinessComponents.EP_Update_General_Settings(EP_BusinessComponents.java:1521)
	at com.bhs.scripts.employeeportal.EP_Home_Tests.EP_MyAccount(EP_Home_Tests.java:146)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- EP_MyAccount -->
  <testcase name="EP_Help_FAQ_Topic_Links" time="42.565" classname="com.bhs.scripts.employeeportal.EP_Home_Tests"/>
  <testcase name="EP_LoadsHelpPage" time="39.469" classname="com.bhs.scripts.employeeportal.EP_Home_Tests"/>
  <testcase name="EP_HomepageNavigation" time="113.905" classname="com.bhs.scripts.employeeportal.EP_Home_Tests"/>
  <testcase name="My_Profile_ensure_funding_links" time="43.141" classname="com.bhs.scripts.employeeportal.EP_Home_Tests"/>
  <testcase name="EP_Add_Payment_Information" time="79.090" classname="com.bhs.scripts.employeeportal.EP_Home_Tests"/>
  <testcase name="Help_Email_Us_Link_Cancel" time="63.201" classname="com.bhs.scripts.employeeportal.EP_Home_Tests">
    <error type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.fail(Assert.java:101)
	at com.bhs.util.REPORTER.LogEvent(REPORTER.java:722)
	at com.bhs.scripts.employeeportal.EP_Home_Tests.Help_Email_Us_Link_Cancel(EP_Home_Tests.java:312)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- Help_Email_Us_Link_Cancel -->
  <testcase name="EP_Feedback_Submit" time="51.260" classname="com.bhs.scripts.employeeportal.EP_Home_Tests"/>
  <testcase name="Help_Email_Us_Link_Submit" time="50.202" classname="com.bhs.scripts.employeeportal.EP_Home_Tests"/>
  <testcase name="EP_General" time="36.623" classname="com.bhs.scripts.employeeportal.EP_Home_Tests"/>
</testsuite> <!-- com.bhs.scripts.employeeportal.EP_Home_Tests -->
